//RECIPEDATA - mock recipe data for "Results" and "Recipes" page - taken from TheMealDB (https://www.themealdb.com/api.php)
const meals = [
  {
    idMeal: "52841",
    strMeal: "Creamy Tomato Soup",
    strDrinkAlternate: null,
    strCategory: "Starter",
    strArea: "British",
    strInstructions:
      "Put the oil, onions, celery, carrots, potatoes and bay leaves in a big casserole dish, or two saucepans. Fry gently until the onions are softened – about 10-15 mins. Fill the kettle and boil it.\r\nStir in the tomato purée, sugar, vinegar, chopped tomatoes and passata, then crumble in the stock cubes. Add 1 litre boiling water and bring to a simmer. Cover and simmer for 15 mins until the potato is tender, then remove the bay leaves. Purée with a stick blender (or ladle into a blender in batches) until very smooth. Season to taste and add a pinch more sugar if it needs it. The soup can now be cooled and chilled for up to 2 days, or frozen for up to 3 months.\r\nTo serve, reheat the soup, stirring in the milk – try not to let it boil. Serve in small bowls with cheesy sausage rolls.",
    strMealThumb:
      "https://www.themealdb.com/images/media/meals/stpuws1511191310.jpg",
    strTags: "Baking",
    strYoutube: "https://www.youtube.com/watch?v=lBhwjjUiFk4",
    strIngredient1: "Olive Oil",
    strIngredient2: "Onions",
    strIngredient3: "Celery",
    strIngredient4: "Carrots",
    strIngredient5: "Potatoes",
    strIngredient6: "Bay Leaf",
    strIngredient7: "Tomato Puree",
    strIngredient8: "Sugar",
    strIngredient9: "White Vinegar",
    strIngredient10: "Chopped Tomatoes",
    strIngredient11: "Passata",
    strIngredient12: "Vegetable Stock Cube",
    strIngredient13: "Whole Milk",
    strIngredient14: "",
    strIngredient15: "",
    strIngredient16: "",
    strIngredient17: "",
    strIngredient18: "",
    strIngredient19: "",
    strIngredient20: "",
    strMeasure1: "3 tbsp",
    strMeasure2: "2 chopped",
    strMeasure3: "2 sticks",
    strMeasure4: "300g",
    strMeasure5: "500g",
    strMeasure6: "4",
    strMeasure7: "5 tblsp ",
    strMeasure8: "2 tblsp ",
    strMeasure9: "2 tblsp ",
    strMeasure10: "1½ kg",
    strMeasure11: "500g",
    strMeasure12: "3",
    strMeasure13: "400ml",
    strMeasure14: "",
    strMeasure15: "",
    strMeasure16: "",
    strMeasure17: "",
    strMeasure18: "",
    strMeasure19: "",
    strMeasure20: "",
    strSource: "https://www.bbcgoodfood.com/recipes/2604646/creamy-tomato-soup",
    strImageSource: null,
    strCreativeCommonsConfirmed: null,
    dateModified: null,
  },
  {
    idMeal: "53045",
    strMeal: "Portuguese fish stew (Caldeirada de peixe)",
    strDrinkAlternate: null,
    strCategory: "Seafood",
    strArea: "Portuguese",
    strInstructions:
      "STEP 1\r\n\r\nHeat a drizzle of oil in a large, deep-sided frying pan, and fry the onion and pepper on a medium heat until softened but not browned. Finely chop the coriander stalks (keep the leaves for later), and add to the pan with the chilli and chopped garlic. Fry for another few minutes. Add the wine, saffron and bay leaf and let it simmer until reduced by half.\r\n\r\nSTEP 2\r\n\r\nAdd the potatoes, tomatoes, and 300ml water and bring to a gentle boil. Break up the tomatoes with a spoon on the side of the pan and simmer for 20-25 minutes until the potatoes are just tender, and the tomatoes have broken down.\r\n\r\nSTEP 3\r\n\r\nSeason well, then gently push the fish into the sauce, and arrange the squid, prawns, clams and mussels on the surface. Put the lid on and cook for 6-8 minutes until the mussel and clam shells have opened, the prawns are cooked and the fish is flaky. Toast the bread, rub lightly with the halved garlic clove and drizzle with olive oil. Serve the stew scatted with chopped coriander leaves, and the toasts for dunking.",
    strMealThumb:
      "https://www.themealdb.com/images/media/meals/do7zps1614349775.jpg",
    strTags: null,
    strYoutube: "https://www.youtube.com/watch?v=utv-GpSJypk",
    strIngredient1: "Onions",
    strIngredient2: "Red Pepper",
    strIngredient3: "Coriander",
    strIngredient4: "Red Chilli",
    strIngredient5: "Garlic",
    strIngredient6: "Dry White Wine",
    strIngredient7: "Saffron",
    strIngredient8: "Bay Leaf",
    strIngredient9: "Potatoes",
    strIngredient10: "Plum Tomatoes",
    strIngredient11: "Cod",
    strIngredient12: "Squid",
    strIngredient13: "Tiger Prawns",
    strIngredient14: "Clams",
    strIngredient15: "Mussels",
    strIngredient16: "Baguette",
    strIngredient17: "",
    strIngredient18: "",
    strIngredient19: "",
    strIngredient20: "",
    strMeasure1: "2 finely chopped",
    strMeasure2: "1 Diced",
    strMeasure3: "Small bunch",
    strMeasure4: "1 small",
    strMeasure5: "3 cloves",
    strMeasure6: "400ml",
    strMeasure7: "Pinch",
    strMeasure8: "1",
    strMeasure9: "300g",
    strMeasure10: "400g",
    strMeasure11: "600g",
    strMeasure12: "300g",
    strMeasure13: "8",
    strMeasure14: "500g",
    strMeasure15: "500g",
    strMeasure16: "1 sliced",
    strMeasure17: " ",
    strMeasure18: " ",
    strMeasure19: " ",
    strMeasure20: " ",
    strSource:
      "https://www.olivemagazine.com/recipes/one-pots/portuguese-fish-stew-caldeirada-de-peixe/",
    strImageSource: null,
    strCreativeCommonsConfirmed: null,
    dateModified: null,
  },
  {
    idMeal: "52886",
    strMeal: "Spotted Dick",
    strDrinkAlternate: null,
    strCategory: "Dessert",
    strArea: "British",
    strInstructions:
      "Put the flour and salt in a bowl. Add the suet, currants, sugar, lemon and orange zest.\r\nPour in 150ml milk and mix to a firm but moist dough, adding the extra milk if necessary.\r\nShape into a fat roll about 20cm long. Place on a large rectangle of baking parchment. Wrap loosely to allow for the pudding to rise and tie the ends with string like a Christmas cracker.\r\nPlace a steamer over a large pan of boiling water, add the pudding to the steamer, cover and steam for 1 1/2 hours. Top up the pan with water from time to time.\r\nRemove from the steamer and allow to cool slightly before unwrapping. Serve sliced with custard.",
    strMealThumb:
      "https://www.themealdb.com/images/media/meals/xqvyqr1511638875.jpg",
    strTags: "Fruity,Pudding,Desert",
    strYoutube: "https://www.youtube.com/watch?v=fu15XOF-ros",
    strIngredient1: "Self-raising Flour",
    strIngredient2: "Salt",
    strIngredient3: "Suet",
    strIngredient4: "Currants",
    strIngredient5: "Caster Sugar",
    strIngredient6: "Lemon",
    strIngredient7: "Orange",
    strIngredient8: "Milk",
    strIngredient9: "Custard",
    strIngredient10: "",
    strIngredient11: "",
    strIngredient12: "",
    strIngredient13: "",
    strIngredient14: "",
    strIngredient15: "",
    strIngredient16: "",
    strIngredient17: "",
    strIngredient18: "",
    strIngredient19: "",
    strIngredient20: "",
    strMeasure1: "250g",
    strMeasure2: "pinch",
    strMeasure3: "125g",
    strMeasure4: "175g",
    strMeasure5: "80g",
    strMeasure6: "Zest of 1",
    strMeasure7: "Zest of 1",
    strMeasure8: "150ml",
    strMeasure9: "to serve",
    strMeasure10: "",
    strMeasure11: "",
    strMeasure12: "",
    strMeasure13: "",
    strMeasure14: "",
    strMeasure15: "",
    strMeasure16: "",
    strMeasure17: "",
    strMeasure18: "",
    strMeasure19: "",
    strMeasure20: "",
    strSource: "https://www.bbcgoodfood.com/recipes/2686661/spotted-dick",
    strImageSource: null,
    strCreativeCommonsConfirmed: null,
    dateModified: null,
  },
  {
    idMeal: "52908",
    strMeal: "Ratatouille",
    strDrinkAlternate: null,
    strCategory: "Vegetarian",
    strArea: "French",
    strInstructions:
      "Cut the aubergines in half lengthways. Place them on the board, cut side down, slice in half lengthways again and then across into 1.5cm chunks. Cut off the courgettes ends, then across into 1.5cm slices. Peel the peppers from stalk to bottom. Hold upright, cut around the stalk, then cut into 3 pieces. Cut away any membrane, then chop into bite-size chunks.\r\nScore a small cross on the base of each tomato, then put them into a heatproof bowl. Pour boiling water over the tomatoes, leave for 20 secs, then remove. Pour the water away, replace the tomatoes and cover with cold water. Leave to cool, then peel the skin away. Quarter the tomatoes, scrape away the seeds with a spoon, then roughly chop the flesh.\r\nSet a sauté pan over medium heat and when hot, pour in 2 tbsp olive oil. Brown the aubergines for 5 mins on each side until the pieces are soft. Set them aside and fry the courgettes in another tbsp oil for 5 mins, until golden on both sides. Repeat with the peppers. Don’t overcook the vegetables at this stage, as they have some more cooking left in the next step.\r\nTear up the basil leaves and set aside. Cook the onion in the pan for 5 mins. Add the garlic and fry for a further min. Stir in the vinegar and sugar, then tip in the tomatoes and half the basil. Return the vegetables to the pan with some salt and pepper and cook for 5 mins. Serve with basil.",
    strMealThumb:
      "https://www.themealdb.com/images/media/meals/wrpwuu1511786491.jpg",
    strTags: "Vegetables,SideDish",
    strYoutube: "https://www.youtube.com/watch?v=BFdQUgAFtGU",
    strIngredient1: "Aubergine",
    strIngredient2: "Courgettes",
    strIngredient3: "Yellow Pepper",
    strIngredient4: "Tomato",
    strIngredient5: "Olive Oil",
    strIngredient6: "Basil",
    strIngredient7: "Onion",
    strIngredient8: "Garlic Clove",
    strIngredient9: "Red Wine Vinegar",
    strIngredient10: "Sugar",
    strIngredient11: "",
    strIngredient12: "",
    strIngredient13: "",
    strIngredient14: "",
    strIngredient15: "",
    strIngredient16: "",
    strIngredient17: "",
    strIngredient18: "",
    strIngredient19: "",
    strIngredient20: "",
    strMeasure1: "2 large",
    strMeasure2: "4",
    strMeasure3: "2",
    strMeasure4: "4 large",
    strMeasure5: "5 tbs",
    strMeasure6: "Bunch",
    strMeasure7: "1 medium",
    strMeasure8: "3 finely chopped",
    strMeasure9: "1 tsp ",
    strMeasure10: "1 tsp ",
    strMeasure11: "",
    strMeasure12: "",
    strMeasure13: "",
    strMeasure14: "",
    strMeasure15: "",
    strMeasure16: "",
    strMeasure17: "",
    strMeasure18: "",
    strMeasure19: "",
    strMeasure20: "",
    strSource: "https://www.bbcgoodfood.com/recipes/2903/ratatouille",
    strImageSource: null,
    strCreativeCommonsConfirmed: null,
    dateModified: null,
  },
  {
    idMeal: "52842",
    strMeal: "Broccoli & Stilton soup",
    strDrinkAlternate: null,
    strCategory: "Starter",
    strArea: "British",
    strInstructions:
      "Heat the rapeseed oil in a large saucepan and then add the onions. Cook on a medium heat until soft. Add a splash of water if the onions start to catch.\r\n\r\nAdd the celery, leek, potato and a knob of butter. Stir until melted, then cover with a lid. Allow to sweat for 5 minutes. Remove the lid.\r\n\r\nPour in the stock and add any chunky bits of broccoli stalk. Cook for 10 – 15 minutes until all the vegetables are soft.\r\n\r\nAdd the rest of the broccoli and cook for a further 5 minutes. Carefully transfer to a blender and blitz until smooth. Stir in the stilton, allowing a few lumps to remain. Season with black pepper and serve.",
    strMealThumb:
      "https://www.themealdb.com/images/media/meals/tvvxpv1511191952.jpg",
    strTags: null,
    strYoutube: "https://www.youtube.com/watch?v=_HgVLpmNxTY",
    strIngredient1: "Rapeseed Oil",
    strIngredient2: "Onion",
    strIngredient3: "Celery",
    strIngredient4: "Leek",
    strIngredient5: "Potatoes",
    strIngredient6: "Butter",
    strIngredient7: "Vegetable Stock",
    strIngredient8: "Broccoli",
    strIngredient9: "Stilton Cheese",
    strIngredient10: "",
    strIngredient11: "",
    strIngredient12: "",
    strIngredient13: "",
    strIngredient14: "",
    strIngredient15: "",
    strIngredient16: "",
    strIngredient17: "",
    strIngredient18: "",
    strIngredient19: "",
    strIngredient20: "",
    strMeasure1: "2 tblsp ",
    strMeasure2: "1 finely chopped ",
    strMeasure3: "1",
    strMeasure4: "1 sliced",
    strMeasure5: "1 medium",
    strMeasure6: "1 knob",
    strMeasure7: "1 litre hot",
    strMeasure8: "1 Head chopped",
    strMeasure9: "140g",
    strMeasure10: "",
    strMeasure11: "",
    strMeasure12: "",
    strMeasure13: "",
    strMeasure14: "",
    strMeasure15: "",
    strMeasure16: "",
    strMeasure17: "",
    strMeasure18: "",
    strMeasure19: "",
    strMeasure20: "",
    strSource:
      "https://www.bbcgoodfood.com/recipes/1940679/broccoli-and-stilton-soup",
    strImageSource: null,
    strCreativeCommonsConfirmed: null,
    dateModified: null,
  },
  {
    idMeal: "52958",
    strMeal: "Peanut Butter Cookies",
    strDrinkAlternate: null,
    strCategory: "Dessert",
    strArea: "American",
    strInstructions:
      "Preheat oven to 350ºF (180ºC).\r\nIn a large bowl, mix together the peanut butter, sugar, and egg.\r\nScoop out a spoonful of dough and roll it into a ball. Place the cookie balls onto a nonstick baking sheet.\r\nFor extra decoration and to make them cook more evenly, flatten the cookie balls by pressing a fork down on top of them, then press it down again at a 90º angle to make a criss-cross pattern.\r\nBake for 8-10 minutes or until the bottom of the cookies are golden brown.\r\nRemove from baking sheet and cool.\r\nEnjoy!",
    strMealThumb: "https://www.themealdb.com/images/media/meals/1544384070.jpg",
    strTags: "Breakfast,UnHealthy,BBQ",
    strYoutube: "",
    strIngredient1: "Peanut Butter",
    strIngredient2: "Sugar",
    strIngredient3: "Egg",
    strIngredient4: "",
    strIngredient5: "",
    strIngredient6: "",
    strIngredient7: "",
    strIngredient8: "",
    strIngredient9: "",
    strIngredient10: "",
    strIngredient11: "",
    strIngredient12: "",
    strIngredient13: "",
    strIngredient14: "",
    strIngredient15: "",
    strIngredient16: "",
    strIngredient17: "",
    strIngredient18: "",
    strIngredient19: "",
    strIngredient20: "",
    strMeasure1: "1 cup ",
    strMeasure2: "1/2 cup ",
    strMeasure3: "1",
    strMeasure4: "",
    strMeasure5: "",
    strMeasure6: "",
    strMeasure7: "",
    strMeasure8: "",
    strMeasure9: "",
    strMeasure10: "",
    strMeasure11: "",
    strMeasure12: "",
    strMeasure13: "",
    strMeasure14: "",
    strMeasure15: "",
    strMeasure16: "",
    strMeasure17: "",
    strMeasure18: "",
    strMeasure19: "",
    strMeasure20: "",
    strSource: "https://tasty.co/recipe/3-ingredient-peanut-butter-cookies",
    strImageSource: null,
    strCreativeCommonsConfirmed: null,
    dateModified: null,
  },
  {
    idMeal: "53009",
    strMeal: "Lamb and Lemon Souvlaki",
    strDrinkAlternate: null,
    strCategory: "Lamb",
    strArea: "Greek",
    strInstructions:
      "Pound the garlic with sea salt in a pestle and mortar (or use a small food processor), until the garlic forms a paste. Whisk together the oil, lemon juice, zest, dill and garlic. Mix in the lamb and combine well. Cover and marinate for at least 2 hrs or overnight in the fridge. If you’re going to use bamboo skewers, soak them in cold water.\r\n\r\nIf you’ve prepared the lamb the previous day, take it out of the fridge 30 mins before cooking. Thread the meat onto the soaked or metal skewers. Heat the grill to high or have a hot griddle pan or barbecue ready. Cook the skewers for 2-3 mins on each side, basting with the remaining marinade. Heat the pitta or flatbreads briefly, then stuff with the souvlaki. Add Greek salad (see 'Goes well with', right) and Tzatziki (below), if you like.",
    strMealThumb:
      "https://www.themealdb.com/images/media/meals/rjhf741585564676.jpg",
    strTags: null,
    strYoutube: "https://www.youtube.com/watch?v=krR4rhjR75Y",
    strIngredient1: "Garlic",
    strIngredient2: "Sea Salt",
    strIngredient3: "Olive Oil",
    strIngredient4: "Lemon",
    strIngredient5: "Dill",
    strIngredient6: "Lamb Leg",
    strIngredient7: "Pita Bread",
    strIngredient8: "",
    strIngredient9: "",
    strIngredient10: "",
    strIngredient11: "",
    strIngredient12: "",
    strIngredient13: "",
    strIngredient14: "",
    strIngredient15: "",
    strIngredient16: "",
    strIngredient17: "",
    strIngredient18: "",
    strIngredient19: "",
    strIngredient20: "",
    strMeasure1: "2 cloves",
    strMeasure2: "2 tsp",
    strMeasure3: "4 tbs",
    strMeasure4: "Zest and juice of 1",
    strMeasure5: "1 tbs",
    strMeasure6: "750g",
    strMeasure7: "To serve",
    strMeasure8: " ",
    strMeasure9: " ",
    strMeasure10: " ",
    strMeasure11: " ",
    strMeasure12: " ",
    strMeasure13: " ",
    strMeasure14: " ",
    strMeasure15: " ",
    strMeasure16: " ",
    strMeasure17: " ",
    strMeasure18: " ",
    strMeasure19: " ",
    strMeasure20: " ",
    strSource: "https://www.bbcgoodfood.com/recipes/lamb-lemon-dill-souvlaki",
    strImageSource: null,
    strCreativeCommonsConfirmed: null,
    dateModified: null,
  },
  {
    idMeal: "52854",
    strMeal: "Pancakes",
    strDrinkAlternate: null,
    strCategory: "Dessert",
    strArea: "American",
    strInstructions:
      "Put the flour, eggs, milk, 1 tbsp oil and a pinch of salt into a bowl or large jug, then whisk to a smooth batter. Set aside for 30 mins to rest if you have time, or start cooking straight away.\r\nSet a medium frying pan or crêpe pan over a medium heat and carefully wipe it with some oiled kitchen paper. When hot, cook your pancakes for 1 min on each side until golden, keeping them warm in a low oven as you go.\r\nServe with lemon wedges and sugar, or your favourite filling. Once cold, you can layer the pancakes between baking parchment, then wrap in cling film and freeze for up to 2 months.",
    strMealThumb:
      "https://www.themealdb.com/images/media/meals/rwuyqx1511383174.jpg",
    strTags: "Breakfast,Desert,Sweet,Fruity",
    strYoutube: "https://www.youtube.com/watch?v=LWuuCndtJr0",
    strIngredient1: "Flour",
    strIngredient2: "Eggs",
    strIngredient3: "Milk",
    strIngredient4: "Sunflower Oil",
    strIngredient5: "Sugar",
    strIngredient6: "Raspberries",
    strIngredient7: "Blueberries",
    strIngredient8: "",
    strIngredient9: "",
    strIngredient10: "",
    strIngredient11: "",
    strIngredient12: "",
    strIngredient13: "",
    strIngredient14: "",
    strIngredient15: "",
    strIngredient16: "",
    strIngredient17: "",
    strIngredient18: "",
    strIngredient19: "",
    strIngredient20: "",
    strMeasure1: "100g ",
    strMeasure2: "2 large",
    strMeasure3: "300ml ",
    strMeasure4: "1 tbls",
    strMeasure5: "to serve",
    strMeasure6: "to serve",
    strMeasure7: "to serve",
    strMeasure8: "",
    strMeasure9: "",
    strMeasure10: "",
    strMeasure11: "",
    strMeasure12: "",
    strMeasure13: "",
    strMeasure14: "",
    strMeasure15: "",
    strMeasure16: "",
    strMeasure17: "",
    strMeasure18: "",
    strMeasure19: "",
    strMeasure20: "",
    strSource: "https://www.bbcgoodfood.com/recipes/2907669/easy-pancakes",
    strImageSource: null,
    strCreativeCommonsConfirmed: null,
    dateModified: null,
  },
  {
    idMeal: "52991",
    strMeal: "Mince Pies",
    strDrinkAlternate: null,
    strCategory: "Dessert",
    strArea: "British",
    strInstructions:
      "To make the pastry, rub 225g cold, diced butter into 350g plain flour, then mix in 100g golden caster sugar and a pinch of salt.\r\n\r\nCombine the pastry into a ball – don’t add liquid – and knead it briefly. The dough will be fairly firm, like shortbread dough. You can use the dough immediately, or chill for later.\r\n\r\nPreheat the oven to 200C/gas 6/fan 180C. Line 18 holes of two 12-hole patty tins, by pressing small walnut-sized balls of pastry into each hole.\r\n\r\nSpoon 280g mincemeat into the pies.\r\n\r\nTake slightly smaller balls of pastry than before and pat them out between your hands to make round lids, big enough to cover the pies. \r\n\r\nTop the pies with their lids, pressing the edges gently together to seal – you don’t need to seal them with milk or egg as they will stick on their own. (The pies may now be frozen for up to 1 month).\r\n\r\nBeat 1 small egg and brush the tops of the pies. Bake for 20 mins until golden. Leave to cool in the tin for 5 mins, then remove to a wire rack.\r\n\r\nTo serve, lightly dust with icing sugar.",
    strMealThumb:
      "https://www.themealdb.com/images/media/meals/qe8pf51576795532.jpg",
    strTags: "Christmas",
    strYoutube: "https://www.youtube.com/watch?v=PnXft7lQNJE",
    strIngredient1: "Butter",
    strIngredient2: "Plain Flour",
    strIngredient3: "Caster Sugar",
    strIngredient4: "Mincemeat",
    strIngredient5: "Egg",
    strIngredient6: "Icing Sugar",
    strIngredient7: "",
    strIngredient8: "",
    strIngredient9: "",
    strIngredient10: "",
    strIngredient11: "",
    strIngredient12: "",
    strIngredient13: "",
    strIngredient14: "",
    strIngredient15: "",
    strIngredient16: "",
    strIngredient17: "",
    strIngredient18: "",
    strIngredient19: "",
    strIngredient20: "",
    strMeasure1: "225g",
    strMeasure2: "350g",
    strMeasure3: "100g ",
    strMeasure4: "280g",
    strMeasure5: "1 small",
    strMeasure6: "Topping",
    strMeasure7: " ",
    strMeasure8: " ",
    strMeasure9: " ",
    strMeasure10: " ",
    strMeasure11: " ",
    strMeasure12: " ",
    strMeasure13: " ",
    strMeasure14: " ",
    strMeasure15: " ",
    strMeasure16: " ",
    strMeasure17: " ",
    strMeasure18: " ",
    strMeasure19: " ",
    strMeasure20: " ",
    strSource:
      "https://www.bbcgoodfood.com/recipes/2174/unbelievably-easy-mince-pies",
    strImageSource: null,
    strCreativeCommonsConfirmed: null,
    dateModified: null,
  },
  {
    idMeal: "53018",
    strMeal: "Bigos (Hunters Stew)",
    strDrinkAlternate: null,
    strCategory: "Pork",
    strArea: "Polish",
    strInstructions:
      "Preheat the oven to 350 degrees F (175 degrees C).\r\n\r\nHeat a large pot over medium heat. Add the bacon and kielbasa; cook and stir until the bacon has rendered its fat and sausage is lightly browned. Use a slotted spoon to remove the meat and transfer to a large casserole or Dutch oven.\r\n\r\nCoat the cubes of pork lightly with flour and fry them in the bacon drippings over medium-high heat until golden brown. Use a slotted spoon to transfer the pork to the casserole. Add the garlic, onion, carrots, fresh mushrooms, cabbage and sauerkraut. Reduce heat to medium; cook and stir until the carrots are soft, about 10 minutes. Do not let the vegetables brown.\r\n\r\nDeglaze the pan by pouring in the red wine and stirring to loosen all of the bits of food and flour that are stuck to the bottom. Season with the bay leaf, basil, marjoram, paprika, salt, pepper, caraway seeds and cayenne pepper; cook for 1 minute.\r\n\r\nMix in the dried mushrooms, hot pepper sauce, Worcestershire sauce, beef stock, tomato paste and tomatoes. Heat through just until boiling. Pour the vegetables and all of the liquid into the casserole dish with the meat. Cover with a lid.\r\n\r\nBake in the preheated oven for 2 1/2 to 3 hours, until meat is very tender.",
    strMealThumb:
      "https://www.themealdb.com/images/media/meals/md8w601593348504.jpg",
    strTags: null,
    strYoutube: "https://www.youtube.com/watch?v=Oqg_cO4s8ik",
    strIngredient1: "Bacon",
    strIngredient2: "Kielbasa",
    strIngredient3: "Pork",
    strIngredient4: "Flour",
    strIngredient5: "Garlic",
    strIngredient6: "Onion",
    strIngredient7: "Mushrooms",
    strIngredient8: "Cabbage",
    strIngredient9: "Sauerkraut",
    strIngredient10: "Red Wine",
    strIngredient11: "Bay Leaf",
    strIngredient12: "Basil",
    strIngredient13: "Marjoram",
    strIngredient14: "Paprika",
    strIngredient15: "Caraway Seed",
    strIngredient16: "Hotsauce",
    strIngredient17: "Beef Stock",
    strIngredient18: "Tomato Puree",
    strIngredient19: "Diced Tomatoes",
    strIngredient20: "Worcestershire Sauce",
    strMeasure1: "2 sliced",
    strMeasure2: "1 lb",
    strMeasure3: "1 lb",
    strMeasure4: "1/4 cup",
    strMeasure5: "3 chopped",
    strMeasure6: "1 Diced",
    strMeasure7: "1 1/2 cup ",
    strMeasure8: "4 cups ",
    strMeasure9: "1 Jar",
    strMeasure10: "1/4 cup",
    strMeasure11: "1",
    strMeasure12: "1 tsp ",
    strMeasure13: "1 tsp ",
    strMeasure14: "1 tbs",
    strMeasure15: "1/8 teaspoon",
    strMeasure16: "1 dash",
    strMeasure17: "5 Cups",
    strMeasure18: "2 tbs",
    strMeasure19: "1 cup ",
    strMeasure20: "1 dash",
    strSource: "https://www.allrecipes.com/recipe/138131/bigos-hunters-stew/",
    strImageSource: null,
    strCreativeCommonsConfirmed: null,
    dateModified: null,
  },
];

export default meals;
