//RECIPEDATA - mock recipe data for "Results" and "Recipes" page - taken from TheMealDB (https://www.themealdb.com/api.php)
const meals = [
  {
    id: "52964",
    name: "Smoked Haddock Kedgeree",

    ingredients: [
      "Butter",
      "Onion",
      "Cardamom",
      "Turmeric",
      "Cinnamon Stick",
      "Bay Leaf",
      "Basmati Rice",
      "Chicken Stock",
      "Smoked Haddock",
      "Eggs",
      "Parsley",
      "Lemon",
    ],

    measures: [
      "50g",
      "1 chopped",
      "3 pods",
      "1/4 tsp",
      "1 small",
      "sprigs of fresh",
      "450g",
      "1 litre",
      "750g",
      "3",
      "3 tblsp chopped",
      "1 chopped",
    ],
    image: "https://www.themealdb.com/images/media/meals/1550441275.jpg",

    instructions: [
      "Melt 50g butter in a large saucepan (about 20cm across), add 1 finely chopped medium onion and cook gently over a medium heat for 5 minutes, until softened but not browned.",
      "Stir in 3 split cardamom pods, ¼ tsp turmeric, 1 small cinnamon stick and 2 bay leaves, then cook for 1 minute.",
      "Tip in 450g basmati rice and stir until it is all well coated in the spicy butter.",
      "Pour in 1 litre chicken or fish stock, add ½ teaspoon salt and bring to the boil, stir once to release any rice from the bottom of the pan. Cover with a close-fitting lid, reduce the heat to low and leave to cook very gently for 12 minutes.",
      "Meanwhile, bring some water to the boil in a large shallow pan. Add 750g un-dyed smoked haddock fillet and simmer for 4 minutes, until the fish is just cooked. Lift it out onto a plate and leave until cool enough to handle.",
      "Hard-boil 3 eggs for 8 minutes.",
      "Flake the fish, discarding any skin and bones. Drain the eggs, cool slightly, then peel and chop.",
      "Uncover the rice and remove the bay leaves, cinnamon stick and cardamom pods if you wish to. Gently fork in the fish and the chopped eggs, cover again and return to the heat for 2-3 minutes, or until the fish has heated through.",
      "Gently stir in almost all the 3 tbsp chopped fresh parsley, and season with a little salt and black pepper to taste. Serve scattered with the remaining parsley and garnished with 1 lemon, cut into wedges.",
    ],
  },
  {
    id: "52962",
    name: "Salmon Eggs Benedict",
    ingredients: [
      "Eggs",
      "White Wine Vinegar",
      "English Muffins",
      "Butter",
      "Smoked Salmon",
      "Lemon Juice",
      "White Wine Vinegar",
      "Egg",
      "Unsalted Butter",
    ],
    measures: [
      "4",
      "2 tbs",
      "2",
      "to serve",
      "8 slices",
      "2 tsp",
      "2 tsp",
      "3 yolks",
      "125g",
    ],
    image: "https://www.themealdb.com/images/media/meals/1550440197.jpg",
    instructions: [
      "First make the Hollandaise sauce. Put the lemon juice and vinegar in a small bowl, add the egg yolks and whisk with a balloon whisk until light and frothy. Place the bowl over a pan of simmering water and whisk until mixture thickens. Gradually add the butter, whisking constantly until thick – if it looks like it might be splitting, then whisk off the heat for a few mins. Season and keep warm.",
      "To poach the eggs, bring a large pan of water to the boil and add the vinegar. Lower the heat so that the water is simmering gently. Stir the water so you have a slight whirlpool, then slide in the eggs one by one. Cook each for about 4 mins, then remove with a slotted spoon.",
      "Lightly toast and butter the muffins, then put a couple of slices of salmon on each half. Top each with an egg, spoon over some Hollandaise and garnish with chopped chives.",
    ],
  },

  {
    id: "52965",
    name: "Breakfast Potatoes",
    ingredients: [
      "Potatoes",
      "Olive Oil",
      "Bacon",
      "Garlic Clove",
      "Maple Syrup",
      "Parsley",
      "Salt",
      "Pepper",
      "Allspice",
    ],
    measures: [
      "3 medium",
      "1 tbs",
      "2 strips",
      "minced",
      "1 tbs",
      "garnish",
      "pinch",
      "pinch",
      "to taste",
    ],
    image: "https://www.themealdb.com/images/media/meals/1550441882.jpg",
    instructions: [
      "Before you do anything, freeze your bacon slices that way when you're ready to prep, it'll be so much easier to chop!",
      "Wash the potatoes and cut medium dice into square pieces. To prevent any browning, place the already cut potatoes in a bowl filled with water.",
      "In the meantime, heat 1-2 tablespoons of oil in a large skillet over medium-high heat. Tilt the skillet so the oil spreads evenly.",
      "Once the oil is hot, drain the potatoes and add to the skillet. Season with salt, pepper, and Old Bay as needed.",
      "Cook for 10 minutes, stirring the potatoes often, until brown. If needed, add a tablespoon more of oil.",
      "Chop up the bacon and add to the potatoes. The bacon will start to render and the fat will begin to further cook the potatoes. Toss it up a bit! The bacon will take 5-6 minutes to crisp.",
      "Once the bacon is cooked, reduce the heat to medium-low, add the minced garlic and toss. Season once more. Add dried or fresh parsley. Control heat as needed.",
      "Let the garlic cook until fragrant, about one minute.",
      "Just before serving, drizzle over the maple syrup and toss. Let that cook another minute, giving the potatoes a caramelized effect.",
      "Serve in a warm bowl with a sunny side up egg!",
    ],
  },
  {
    id: "52896",
    name: "Full English Breakfast",
    ingredients: [
      "Sausages",
      "Bacon",
      "Mushrooms",
      "Tomatoes",
      "Black Pudding",
      "Eggs",
      "Bread",
      "Baked Beans",
    ],
    measures: ["4", "4", "4", "3", "2 sliced", "2", "1 slice", "100g "],
    image: "https://www.themealdb.com/images/media/meals/sqrtwu1511721265.jpg",
    instructions: [
      "Heat the flat grill plate over a low heat, on top of 2 rings/flames if it fits, and brush sparingly with light olive oil.",
      "Cook the sausages first. Add the sausages to the hot grill plate/the coolest part if there is one and allow to cook slowly for about 15-20 minutes, turning occasionally, until golden. After the first 10 minutes, increase the heat to medium before beginning to cook the other ingredients. If you are struggling for space, completely cook the sausages and keep hot on a plate in the oven.",
      "Snip a few small cuts into the fatty edge of the bacon. Place the bacon straight on to the grill plate and fry for 2-4 minutes each side or until your preferred crispiness is reached. Like the sausages, the cooked bacon can be kept hot on a plate in the oven.",
      "For the mushrooms, brush away any dirt using a pastry brush and trim the stalk level with the mushroom top. Season with salt and pepper and drizzle over a little olive oil. Place stalk-side up on the grill plate and cook for 1-2 minutes before turning and cooking for a further 3-4 minutes. Avoid moving the mushrooms too much while cooking, as this releases the natural juices, making them soggy.",
      "For the tomatoes, cut the tomatoes across the centre/or in half lengthways if using plum tomatoes , and with a small, sharp knife remove the green 'eye'. Season with salt and pepper and drizzle with a little olive oil. Place cut-side down on the grill plate and cook without moving for 2 minutes. Gently turn over and season again. Cook for a further 2-3 minutes until tender but still holding their shape.",
      "For the black pudding, cut the black pudding into 3-4 slices and remove the skin. Place on the grill plate and cook for 1½-2 minutes each side until slightly crispy.",
      "For 'proper' fried bread it's best to cook it in a separate pan. Ideally, use bread that is a couple of days old. Heat a frying pan to a medium heat and cover the base with oil. Add the bread and cook for 2-3 minutes each side until crispy and golden. If the pan becomes too dry, add a little more oil. For a richer flavour, add a knob of butter after you turn the slice.",
      "For the fried eggs, break the egg straight into the pan with the fried bread and leave for 30 seconds. Add a good knob of butter and lightly splash/baste the egg with the butter when melted. Cook to your preferred stage, season and gently remove with a fish slice.",
      "Once all the ingredients are cooked, serve on warm plates and enjoy straight away with a good squeeze of tomato ketchup or brown sauce.",
    ],
  },
  {
    id: "52957",
    name: "Fruit And Cream Cheese Breakfast Pastries",
    ingredients: [
      "Cream Cheese",
      "Sugar",
      "Vanilla Extract",
      "Flour",
      "Puff Pastry",
      "Strawberries",
      "Raspberries",
      "Blackberries",
    ],
    measures: [
      "1 1/4 oz ",
      "1 1/4 cup",
      "1 teaspoon",
      null,
      "2",
      null,
      null,
      null,
    ],
    image: "https://www.themealdb.com/images/media/meals/1543774956.jpg",
    instructions: [
      "Preheat oven to 400ºF (200ºC), and prepare two cookie sheets with parchment paper. In a bowl, mix cream cheese, sugar, and vanilla until fully combined. Lightly flour the surface and roll out puff pastry on top to flatten. Cut each sheet of puff pastry into 9 equal squares. On the top right and bottom left of the pastry, cut an L shape approximately ½ inch (1 cm) from the edge.",
      "NOTE: This L shape should reach all the way down and across the square, however both L shapes should not meet at the ends. Your pastry should look like a picture frame with two corners still intact.",
      "Take the upper right corner and fold down towards the inner bottom corner. You will now have a diamond shape.",
      "Place 1 to 2 teaspoons of the cream cheese filling in the middle, then place berries on top.",
      "Repeat with the remaining pastry squares and place them onto the parchment covered baking sheet.",
      "Bake for 15-20 minutes or until pastry is golden brown and puffed.",
    ],
  },
  {
    id: "52895",
    name: "English Breakfast",
    ingredients: [
      "Sausages",
      "Bacon",
      "Mushrooms",
      "Tomatoes",
      "Black Pudding",
      "Eggs",
      "Bread",
    ],
    measures: ["2", "3", "2", "2", "1 slice", "2", "1 slice"],
    image: "https://www.themealdb.com/images/media/meals/utxryw1511721587.jpg",
    instructions: [
      "Heat the flat grill plate over a low heat, on top of 2 rings/flames if it fits, and brush sparingly with light olive oil.",
      "Cook the sausages first. Add the sausages to the hot grill plate/the coolest part if there is one and allow to cook slowly for about 15-20 minutes, turning occasionally, until golden. After the first 10 minutes, increase the heat to medium before beginning to cook the other ingredients. If you are struggling for space, completely cook the sausages and keep hot on a plate in the oven.",
      "Snip a few small cuts into the fatty edge of the bacon. Place the bacon straight on to the grill plate and fry for 2-4 minutes each side or until your preferred crispiness is reached. Like the sausages, the cooked bacon can be kept hot on a plate in the oven.",
      "For the mushrooms, brush away any dirt using a pastry brush and trim the stalk level with the mushroom top. Season with salt and pepper and drizzle over a little olive oil. Place stalk-side up on the grill plate and cook for 1-2 minutes before turning and cooking for a further 3-4 minutes. Avoid moving the mushrooms too much while cooking, as this releases the natural juices, making them soggy.",
      "For the tomatoes, cut the tomatoes across the centre/or in half lengthways if using plum tomatoes , and with a small, sharp knife remove the green 'eye'. Season with salt and pepper and drizzle with a little olive oil. Place cut-side down on the grill plate and cook without moving for 2 minutes. Gently turn over and season again. Cook for a further 2-3 minutes until tender but still holding their shape.",
      "For the black pudding, cut the black pudding into 3-4 slices and remove the skin. Place on the grill plate and cook for 1½-2 minutes each side until slightly crispy.",
      "For 'proper' fried bread it's best to cook it in a separate pan. Ideally, use bread that is a couple of days old. Heat a frying pan to a medium heat and cover the base with oil. Add the bread and cook for 2-3 minutes each side until crispy and golden. If the pan becomes too dry, add a little more oil. For a richer flavour, add a knob of butter after you turn the slice.",
      "For the fried eggs, break the egg straight into the pan with the fried bread and leave for 30 seconds. Add a good knob of butter and lightly splash/baste the egg with the butter when melted. Cook to your preferred stage, season and gently remove with a fish slice.",
      "Once all the ingredients are cooked, serve on warm plates and enjoy straight away with a good squeeze of tomato ketchup or brown sauce.",
    ],
  },
];
export default meals;
